with-expecter: true
packages:
  github.com/kanthorlabs/common/cache:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Cache:
  github.com/kanthorlabs/common/circuitbreaker:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      CircuitBreaker:
  github.com/kanthorlabs/common/clock:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Clock:
  github.com/kanthorlabs/common/logging:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Logger:
  github.com/kanthorlabs/common/idempotency:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Idempotency:
  github.com/kanthorlabs/common/passport:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Passport:
  github.com/kanthorlabs/common/gatekeeper:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Gatekeeper:
  github.com/nats-io/nats.go/jetstream:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      JetStream:
