with-expecter: true
packages:
  github.com/kanthorlabs/common/logging:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Logger:
  github.com/kanthorlabs/common/timer:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Timer:
  github.com/kanthorlabs/common/passport:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Passport:
  github.com/kanthorlabs/common/gatekeeper:
    config:
      filename: "{{ .InterfaceName | snakecase }}.go"
      dir: "mocks/{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      Gatekeeper:
