// Code generated by mockery v2.41.0. DO NOT EDIT.

package passport

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	strategies "github.com/kanthorlabs/common/passport/strategies"
)

// Passport is an autogenerated mock type for the Passport type
type Passport struct {
	mock.Mock
}

type Passport_Expecter struct {
	mock *mock.Mock
}

func (_m *Passport) EXPECT() *Passport_Expecter {
	return &Passport_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: ctx
func (_m *Passport) Connect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Passport_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type Passport_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Passport_Expecter) Connect(ctx interface{}) *Passport_Connect_Call {
	return &Passport_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *Passport_Connect_Call) Run(run func(ctx context.Context)) *Passport_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Passport_Connect_Call) Return(_a0 error) *Passport_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Passport_Connect_Call) RunAndReturn(run func(context.Context) error) *Passport_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields: ctx
func (_m *Passport) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Passport_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type Passport_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Passport_Expecter) Disconnect(ctx interface{}) *Passport_Disconnect_Call {
	return &Passport_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *Passport_Disconnect_Call) Run(run func(ctx context.Context)) *Passport_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Passport_Disconnect_Call) Return(_a0 error) *Passport_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Passport_Disconnect_Call) RunAndReturn(run func(context.Context) error) *Passport_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Liveness provides a mock function with given fields:
func (_m *Passport) Liveness() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Liveness")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Passport_Liveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Liveness'
type Passport_Liveness_Call struct {
	*mock.Call
}

// Liveness is a helper method to define mock.On call
func (_e *Passport_Expecter) Liveness() *Passport_Liveness_Call {
	return &Passport_Liveness_Call{Call: _e.mock.On("Liveness")}
}

func (_c *Passport_Liveness_Call) Run(run func()) *Passport_Liveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Passport_Liveness_Call) Return(_a0 error) *Passport_Liveness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Passport_Liveness_Call) RunAndReturn(run func() error) *Passport_Liveness_Call {
	_c.Call.Return(run)
	return _c
}

// Readiness provides a mock function with given fields:
func (_m *Passport) Readiness() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Readiness")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Passport_Readiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readiness'
type Passport_Readiness_Call struct {
	*mock.Call
}

// Readiness is a helper method to define mock.On call
func (_e *Passport_Expecter) Readiness() *Passport_Readiness_Call {
	return &Passport_Readiness_Call{Call: _e.mock.On("Readiness")}
}

func (_c *Passport_Readiness_Call) Run(run func()) *Passport_Readiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Passport_Readiness_Call) Return(_a0 error) *Passport_Readiness_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Passport_Readiness_Call) RunAndReturn(run func() error) *Passport_Readiness_Call {
	_c.Call.Return(run)
	return _c
}

// Strategy provides a mock function with given fields: name
func (_m *Passport) Strategy(name string) (strategies.Strategy, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Strategy")
	}

	var r0 strategies.Strategy
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (strategies.Strategy, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) strategies.Strategy); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(strategies.Strategy)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Passport_Strategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Strategy'
type Passport_Strategy_Call struct {
	*mock.Call
}

// Strategy is a helper method to define mock.On call
//   - name string
func (_e *Passport_Expecter) Strategy(name interface{}) *Passport_Strategy_Call {
	return &Passport_Strategy_Call{Call: _e.mock.On("Strategy", name)}
}

func (_c *Passport_Strategy_Call) Run(run func(name string)) *Passport_Strategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Passport_Strategy_Call) Return(_a0 strategies.Strategy, _a1 error) *Passport_Strategy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Passport_Strategy_Call) RunAndReturn(run func(string) (strategies.Strategy, error)) *Passport_Strategy_Call {
	_c.Call.Return(run)
	return _c
}

// NewPassport creates a new instance of Passport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPassport(t interface {
	mock.TestingT
	Cleanup(func())
}) *Passport {
	mock := &Passport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
