name: Test CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 3s
          --health-timeout 3s
          --health-retries 30
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.21"

      - name: test
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.61.0/opa_linux_amd64_static
          sudo mv opa /usr/bin/opa
          sudo chmod +x /usr/bin/opa

          bash scripts/ci_test.sh
          bash scripts/ci_coverage.sh

      - name: coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: golang
          file: cover.out
